language: node_js
node_js:
  - "10.7.0"
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - ./deploy.sh
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fronts
  on:
    branch: master